INTERNET_ACCESS: false  # Set to true to enable internet access
MAX_SEARCH_RESULTS: 10
# Set the maximum search results for internet access DONT SET TOO HIGH

ALLOW_DM: false # Set to true to allow direct messages
SMART_MENTION: true # Set to true to enable smart mention feature

GPT_MODEL: gpt-4o-mini

MAX_HISTORY: 60

PRESENCES_CHANGE_DELAY: 500 # Please note that the Presences Change Delay is measured in seconds. It is advisable not to set it too low, as doing so may result in your bot being rate-limited by Discord
AI_NSFW_CONTENT_FILTER: true # Enable NSFW AI detector to detect NSFW prompt on Imagine Command

LANGUAGE: en # Specify the language code (check 'lang' folder for valid codes)

INSTRUCTIONS: avernus # Specify the instruction prompt to use (check 'instructions' folder for valid prompts)
# To add custom prompts, create a .txt file like 'custom.txt' in `instructions` folder and set INSTRUCTIONS as 'custom'

Discord: ???
Github: ???

TRIGGER:
  - chatbot
  - bot nickname
  - bot alias
  - bot name
  - Other bot alias...

DISABLE_PRESENCE: false
PRESENCES:
  - Vs Code
  - Minecraft
  - Geometry Dash
  - Candy crush
  - OSU!
  - Discord
  - Termux
  - Firefox
  - Task Manager
  - htop
 #List of different presences to be used

OCR_MODEL_URLS:
  - "https://api-inference.huggingface.co/models/microsoft/trocr-base-printed"
  - "https://api-inference.huggingface.co/models/nlpconnect/vit-gpt2-image-captioning"
# List of URLs for OCR models

BLACKLIST_WORDS:
   - milf
   - what
   - centipede
   - loli
   - hentai
   - explicit
   - pornography
   - adult
   - XXX
   - sex
   - erotic
   - black
# Blacklisted words for /Imagine command this is disabled if you enable AI_NSFW_CONTENT_FILTER


IMAGE_FILTER_DEFAULT:
  - low quality
